### ISSUE TITLE
This is brilliant

### ISSUE THREAD

**Issue by cseelus** [LessonPlanet/date_params#3]
Thanks!

Does only work with older Rails projects (<= 3.0 though) because of `before_filter`.

Is there a reason this isn't maintained anymore/would a PR be accepted?

**Comment by razvan-sv** [comment]
Hello,

`before_filter` is available in all Rails versions. What's the issue?

**Comment by cseelus** [comment]
`before_filter` is [deprecated](https://apidock.com/rails/ActionController/Filters/ClassMethods/before_filter) in favor of `before_action` afaik since 3.0 and removed with 5.1 or earlier. 

A Rails 5.2 test app I tried this gem with throws `undefined method 'before_filter' for ApplicationController:Class Did you mean? before_action`.

**Comment by jrust** [comment]
A PR would be accepted; even better is if someone would like to take ownership of the project as I no longer have time to maintain it 😃

**Comment by softbrada** [comment]
this was fixed in https://github.com/LessonPlanet/date_params/pull/4
